=== Soontao/EasyORM/src/test/resources/easyorm.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT easyorm (configure)>
<!ELEMENT configure (dao?,database?,mapper*)>
<!ELEMENT mapper EMPTY>
<!ELEMENT dao EMPTY>
<!ELEMENT database (db_name?,db_driver,db_url,db_username,db_password)>
<!ELEMENT db_name (#PCDATA)>
<!ELEMENT db_driver (#PCDATA)>
<!ELEMENT db_url (#PCDATA)>
<!ELEMENT db_username (#PCDATA)>
<!ELEMENT db_password (#PCDATA)>
<!ATTLIST dao daopackage CDATA #IMPLIED>
<!ATTLIST dao mapperxmlpackage CDATA #IMPLIED>
<!ATTLIST mapper id ID #REQUIRED>
<!ATTLIST mapper location CDATA #REQUIRED>

=== Soontao/EasyORM/target/test-classes/xmltest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE easyorm SYSTEM "easyorm.dtd">
<easyorm>
	<configure>
		<dao daopackage="org.suntao.easyorm.testDAO" mapperxmlpackage="/org/suntao/orm/mapper"></dao>
		<database>
			<db_name>MySQL</db_name>
			<db_driver>com.mysql.jdbc.Driver</db_driver>
			<db_url>jdbc:mysql://42.96.206.67:3306/stu?useUnicode=true&amp;characterEncoding=UTF-8</db_url>
			<db_username>stu</db_username>
			<db_password>admin</db_password>
		</database>
		<mapper id="usermapper" location="org/suntao/mapper/usermapper.xml" />
		<mapper id="courseinfomapper" location="org/suntao/mapper/courseinfomapper.xml" />
	</configure>
</easyorm>
